// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXc4-6xlyK-qLaFJw-Fu1KFA_5Vx1uGi8',
    appId: '1:345686924396:web:87f63b5f7e86357e7e0c49',
    messagingSenderId: '345686924396',
    projectId: 'crmyoobe',
    authDomain: 'crmyoobe.firebaseapp.com',
    storageBucket: 'crmyoobe.firebasestorage.app',
    measurementId: 'G-07X0WWVJVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl2tq15maqqCrJvNck6D2gxfHqMDUTdL8',
    appId: '1:345686924396:android:98e830f7cc87e9827e0c49',
    messagingSenderId: '345686924396',
    projectId: 'crmyoobe',
    storageBucket: 'crmyoobe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '345686924396',
    projectId: 'crmyoobe',
    storageBucket: 'crmyoobe.firebasestorage.app',
    iosBundleId: 'com.yoobe.crm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: '345686924396',
    projectId: 'crmyoobe',
    storageBucket: 'crmyoobe.firebasestorage.app',
    iosBundleId: 'com.yoobe.crm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: '345686924396',
    projectId: 'crmyoobe',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'YOUR_LINUX_API_KEY',
    appId: 'YOUR_LINUX_APP_ID',
    messagingSenderId: '345686924396',
    projectId: 'crmyoobe',
  );
}
